### ISSUE TITLE
Problem with scrolling long Project profiles list

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#100]
The Projects profiles can not be seen, when profile list i long
![image](https://user-images.githubusercontent.com/50234893/79694504-e2214280-8270-11ea-886a-0ca1621c2fcb.png)

The section "project profiles" disappears when a profile is deleted
![image](https://user-images.githubusercontent.com/50234893/79694554-36c4bd80-8271-11ea-8280-cba70575277e.png)

**Comment by mapcentia** [comment]
@JacobBirk @olemunch Disse skule være fixed nu
