### ISSUE TITLE
Project timeseries & profiles lists not always showing

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#102]
Project timeseries & profiles lists are not always visible when you activate a project. It happens when you create a project and just thereafter activates it. It works fine you refresh the browser and when activates the project. Take a look here: https://monosnap.com/file/25wCbT38UABHJxIqZ4gqr7VxvWLS5w?idx=0&total=5 

Also the Project timeseries list is not updating when activating a second project. Take a look here: https://monosnap.com/file/DKWIpCRxBgutKqLAFZUA8Cx0rTbeSX

I guess Project profiles list behaves in the same manner - please check

**Comment by mapcentia** [comment]
@JacobBirk Det ser ud til, at virke som det skal I nyeste version, som er rullet ud. Vil tjekke og evt. lukke dette issue.

**Comment by mapcentia** [comment]
@JacobBirk Det du beskriver sker kun hvis man opretter projektet  og afspiller det umiddelbart efter uden at refreshe browseren. Det er derfor det virker fra startdialog.

**Comment by mapcentia** [comment]
@olemunch @JacobBirk fixed
