### ISSUE TITLE
Project timeseries & profiles 2

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#103]
After load of project the timeseries & profiles should be "checked" in the list
![image](https://user-images.githubusercontent.com/50234893/79712701-e464ba80-82cb-11ea-81de-f210602657f6.png)

Add a "ad to my own" bottom that will clone the timeserie or profile to the user
![image](https://user-images.githubusercontent.com/50234893/79712812-2f7ecd80-82cc-11ea-9edb-5ee433d91bca.png)

**Comment by mapcentia** [comment]
@JacobBirk Det øverste er fixed - jeg var selv opmærksom på det. Jeg opretter et nyt issue med kloning
