### ISSUE TITLE
Mismatch between timeseries in datamenu and in right side menu 

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#108]
![image](https://user-images.githubusercontent.com/50234893/80447377-8b270780-8919-11ea-90de-b067f15e38be.png)

**Comment by mapcentia** [comment]
@aswinm The data-dialog shows only un-archived timeseries to begin with. But after you e.g. create a new one it will reload with the archived ones also. Actually the list the dialog should always only show un-archived timeseries - regardless whatever the user has chosen in the right slide panel.

https://monosnap.com/file/85EMoOXkz6RAJqYP1hzgl5lp6ErLTA

**Comment by mapcentia** [comment]
@aswinm It works. Closing
