### ISSUE TITLE
Redesign of borehole dialog

### ISSUE THREAD

**Issue by mapcentia** [mapcentia/watsonc#114]
Now, then you click on a borehole it looks like this:
![image](https://user-images.githubusercontent.com/3850918/82115795-472f6180-9765-11ea-821e-dc91c105e4db.png)

It should be changed to look like this:
![image](https://user-images.githubusercontent.com/3850918/82115938-3fbc8800-9766-11ea-94e1-96ea9bdb9dc2.png)

**Comment by mapcentia** [comment]
@JacobBirk Den relative overskridelse er nu på plads. Her er et eksempel. tallene i () er debug-info, som skal fjernes igen. Fx "Seneste: 2.03 (203/100)" er 2.03 forholdet mellem den absolute måling (203) og grænseværdien (100). Spørgsmål: 

- Skal maksværdi stadig være med? 
- Og skal den også være relativ?

![image](https://user-images.githubusercontent.com/3850918/84024928-048b2e80-a98b-11ea-85a2-44ed22239239.png)

**Comment by JacobBirk** [comment]
Ja, maks skal med på samme måde

Jacob
________________________________
Fra: MapCentia <notifications@github.com>
Sendt: Monday, June 8, 2020 1:27:22 PM
Til: mapcentia/watsonc <watsonc@noreply.github.com>
Cc: Jacob Birk Jensen <jbj@watsonc.dk>; Mention <mention@noreply.github.com>
Emne: Re: [mapcentia/watsonc] Redesign of borehole dialog (#114)


@JacobBirk<https://github.com/JacobBirk> Den relative overskridelse er nu på plads. Her er et eksempel. tallene i () er debug-info, som skal fjernes igen. Fx "Seneste: 2.03 (203/100)" er 2.03 forholdet mellem den absolute måling (203) og grænseværdien (100). Spørgsmål:

  *   Skal maksværdi stadig være med?
  *   Og skal den også være relativ?

[image]<https://user-images.githubusercontent.com/3850918/84024928-048b2e80-a98b-11ea-85a2-44ed22239239.png>
