### ISSUE TITLE
Fejl ved load af projekt

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#121]
@mapcentia  
En kritisk fejl til listen
Følgende fejl fås med load af https://map.calypso.watsonc.dk/app/jupiter/chemicals,sensor,system/?state=state_snapshot_6112d280-62a9-11ea-8520-673b799241b0

![image](https://user-images.githubusercontent.com/50234893/83026720-a88de500-a02f-11ea-8067-bad989ade027.png)

**Comment by mapcentia** [comment]
@JacobBirk Fejlen er nu fjernet - det var en noget url-encoding, som ikke blev afkodet.
