### ISSUE TITLE
Make sure Profiles has a lower z-index than boreholes

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#122]
The z-index for profile-lines/buffers layers and borehole layers is not controlled. Therefore mouse-over and clicks on boreholes get caught by profile-layers (if they are added after the borehole layers).

Make sure, that profile layers always has a lower z-index than borehole layers. https://leafletjs.com/reference-1.6.0.html#layergroup-setzindex

![image](https://user-images.githubusercontent.com/50234893/83108518-37e2d900-a0c0-11ea-9808-cf5b1472a9b9.png)

**Comment by mapcentia** [comment]
Is not doable
