### ISSUE TITLE
Borehold (datamenu) dialog: search

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#132]
After drag&drop the search  is reset. 
Drag&drop should not reset search 
![image](https://user-images.githubusercontent.com/50234893/84355905-ae550000-abc3-11ea-8b6c-60cdf628ef3c.png)
 
![image](https://user-images.githubusercontent.com/50234893/84355978-d04e8280-abc3-11ea-9cd9-58ee2552392c.png)

![image](https://user-images.githubusercontent.com/50234893/84356025-e4927f80-abc3-11ea-8619-5720df0d048a.png)

**Comment by mapcentia** [comment]
@JacobBirk Jeg lukker denne her, da den er håndteret i #133
