### ISSUE TITLE
Borehold (datamenu) dialog: Keep scroll position after drag&drop

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#133]
Scroll position before drag&drop
![image](https://user-images.githubusercontent.com/50234893/84356663-ce38f380-abc4-11ea-8ab8-cd15072e124e.png)
Scroll position after drag&drop
![image](https://user-images.githubusercontent.com/50234893/84356716-e446b400-abc4-11ea-837a-05fbf277d15b.png)

Keep scroll position (and selected borehole) after drag&drop

**Comment by mapcentia** [comment]
@JacobBirk @olemunch Aswin er i gang med at undersøge muligheden med at gemme tilstanden og efter re-rendering af dialogen, så apply tilstanden igen

**Comment by mapcentia** [comment]
@aswinm The whole dialog is reset after changing state. Could the current state before the change be stored and re-applied after the change?
![Peek 2020-10-03 08-17](https://user-images.githubusercontent.com/3850918/94984859-0b990680-0551-11eb-8ded-97121de13019.gif)
