### ISSUE TITLE
Changes to datamenu/borehole menu

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#135]
![image](https://user-images.githubusercontent.com/50234893/84597036-66eb9f80-ae61-11ea-8c65-66b21a607de3.png)
Fold/unfold: Fold collapses all groups except the group with current compound. Unfold => all groups

**Comment by mapcentia** [comment]
@aswinm It's seems to work OK, but there are a couple of issues:

The checkbox in the dialog and the one in the right slide panel should always be in sync. Meaning, if you check off one, the other should also be checked off:

![image](https://user-images.githubusercontent.com/3850918/87124785-ac955f80-c289-11ea-8374-bc2f9f10ffff.png)
