### ISSUE TITLE
Tilføj "dataanalyse" lag

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#140]
![image](https://user-images.githubusercontent.com/50234893/85400079-23c3b780-b558-11ea-9431-a46ccd396e39.png)

**Comment by WatsonC-hub** [comment]
@mapcentia 
30-06-2020 kl 11.05
Laget er lige nu placeret i jupiter.chemicals.pesticidoverblik men vil blive flyttet til jupiter.analyser.pesticidoverblik

classmax og classlate fortæller hvilken farve venstre og højre halvdel af cirklen skal have (0: grøn, 1: gul, 2: rød)

Her er en forklarling på det JSON-objekt som skal bruges til at danne mouseover:
![image](https://user-images.githubusercontent.com/51744106/86106888-6ab62d80-bac1-11ea-9dde-5a3b068abecd.png)

Lige pt mangler der en "attribut_x" og en attribut_y som skal vises foran værdier - den er på vej...

**Comment by WatsonC-hub** [comment]
@mapcentia 
Update
"attribute" er med i mouseover-strukturen. Det er KUN seneste prøver som attribute skal bruges til. Max prøver er alle over detektionsgrænsen - ellers ville de slet ikke være med i tabellen.

Hvis en boring er Grøn på begge sider så er der ingen mouseover fordi mouseover kun viser en liste af fund af pesticider. I stedet skal der bare stå "ingen pesticidfund"


![image](https://user-images.githubusercontent.com/51744106/86226483-07450200-bb8c-11ea-8b43-db6728f7b7c5.png)
