### ISSUE TITLE
Rapport i højre menu

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#148]
@mapcentia: retter du til til Aswin?

Ny report indgang i højre menu 
![image](https://user-images.githubusercontent.com/50234893/90485045-4b3d9780-e137-11ea-9897-c253ca977cd6.png)
Foldet ud:
![image](https://user-images.githubusercontent.com/50234893/90485157-745e2800-e137-11ea-8534-c1d72168c3ac.png)
Under vælg rapport er der kun mulighed for at vælge "Pesticidoverblik"

**Comment by mapcentia** [comment]
@JacobBirk @olemunch Dialog er rullet ud på test
