### ISSUE TITLE
kan ikke loade andre calypso lag efter at pesticidlaget har været loaded

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#151]
![image](https://user-images.githubusercontent.com/50234893/91128135-e7bbe880-e6a7-11ea-9c7e-2fcff483eb6e.png)

**Comment by mapcentia** [comment]
@JacobBirk Jeg kan ikke genskabe denne fejl:

![Peek 2020-08-25 13-59](https://user-images.githubusercontent.com/3850918/91171817-739b3800-e6db-11ea-99a6-121ec085e261.gif)
