### ISSUE TITLE
UTM-zone 33 fejler i profilværktøj

### ISSUE THREAD

**Issue by WatsonC-hub** [mapcentia/watsonc#152]
Hej Martin

Denne fejl er dukket op igen i profilværktøjet
Et profil på østsjælland sender utm-zone 33 koordinater til profilværktøjet i stedet for utm32
'coordinates':[[341443.7943197296,6201709.576736153],[343103.9923335699,6201706.077921331]],'DGU_nr':[],'Profile_depth':-100,'layers':['/root/vidi/extensions/watsonc/scripts/intersection/../profil/Sjaelland_config.txt'],'overlap':[[[-1661,1661]]]}\""]}

**Comment by mapcentia** [comment]
@olemunch Vil du se om fejlen er fixed på test: https://watsonc-test.vidi.gc2.io/app/jupiter/chemicals,sensor,system/#osm/8/9.668/56.17/chemicals.boreholes_time_series_without_chemicals

**Comment by olemunch** [comment]
Ja - det er fixed på test - har lige tjekket

**Comment by mapcentia** [comment]
@olemunch vil du også teste på prod?

**Comment by olemunch** [comment]
@mapcentia 
Ja - det virker nu. Jeg lukker issue
