### ISSUE TITLE
Nyt rapport ikon

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#155]
@mapcentia Skift kolbe-symbolet med fx dette
![rapport ikon](https://user-images.githubusercontent.com/50234893/92350948-bb0dc500-f0da-11ea-97a9-3fb2adca8a67.png)

**Comment by mapcentia** [comment]
@JacobBirk Der disse at vælge i mellem: https://fontawesome.com/v4.7.0/icons/

Jeg har valgt Excel ikonet: https://fontawesome.com/v4.7.0/icon/file-excel-o
