### ISSUE TITLE
Enheder er forkerte i datamenu

### ISSUE THREAD

**Issue by olemunch** [mapcentia/watsonc#156]
I datamenuen skal enheder hentes fra codes.compunds_view.unit
Lige nu vises kun mg/L

![image](https://user-images.githubusercontent.com/51031638/92442524-57ee6200-f1b0-11ea-9233-7bc37ca53e14.png)

**Comment by WatsonC-hub** [comment]
@mapcentia 
Jeg har tjekket op på enheder og mener de er korrekte i databasen

Eksempel Bam i boring ' 34. 1677'
Enheden er korrekt i "boreholes_time_series_with_chemicals":
Jeg har udtrukket denne:
SELECT _2712 FROM chemicals.boreholes_time_series_with_chemicals
where boreholeno =' 34. 1677'

men enheden vises forkert i datamenu
![image](https://user-images.githubusercontent.com/51744106/93438190-3fc3c480-f8cd-11ea-8524-2d88367223ae.png)

Derfor tænker jeg at fejlen må ligge i CALYPSO-koden? Hvor skulle datamenuen ellers trække enheden fra?

**Comment by WatsonC-hub** [comment]
@mapcentia 

Her er indholdet af SELECT _2712 FROM chemicals.boreholes_time_series_with_chemicals where boreholeno =' 34. 1677':
{
    "unit": "µg/l",
    "title": "2,6-Dichlorbenzamid",
    "intakes": [
        1
    ],
    "attributes": [
        [
            null,
            null,
            "<",
            "<",
            null,
            "<",
            "<",
            "<",
            "<"
        ]
    ],
    "boreholeno": " 34. 1677",
    "measurements": [
        [
            0.014,
            0.015,
            0.01,
            0.01,
            0.013,
            0.01,
            0.01,
            0.01,
            0.01
        ]
    ],
    "timeOfMeasurement": [
        [
            "2000-09-11T09:55:00",
            "2002-09-18T10:55:00",
            "2003-09-22T10:15:00",
            "2006-10-18T10:45:00",
            "2011-05-09T12:00:00",
            "2012-12-18T10:05:00",
            "2013-06-25T09:45:00",
            "2018-09-18T10:35:00",
            "2019-03-05T08:40:00"
        ]
    ]
}
