### ISSUE TITLE
Profilværktøj - intersection tool kan ikke kaldes

### ISSUE THREAD

**Issue by olemunch** [mapcentia/watsonc#157]
@mapcentia 
Profilværktøjet går i stå når intersectionværktøjet kaldes. Der sker ikke noget...
testet 09-09-2020 kl 20.30

**Comment by mapcentia** [comment]
@olemunch Jeg ser denne:
`message: "Traceback (most recent call last):↵  File "/root/vidi/extensions/watsonc/scripts/profil/profiletool_kemi_v5.py", line 998, in <module>↵    profiletool_v5(json_str)↵  File "/root/vidi/extensions/watsonc/scripts/profil/profiletool_kemi_v5.py", line 627, in profiletool_v5↵    if intakes[intakes['boreholeno']== i].intakeno.unique()[0]!=None: # test om der er intag↵IndexError: index 0 is out of bounds for axis 0 with size 0↵"
`
Siger det dig noget?

**Comment by olemunch** [comment]
@mapcentia 
Jeg kommenterede ikke da profilværktøjet ser ud til at virke igen.
Jeg ved ikke helt hvad fejlen betyder. Det ser egentlig ud til at [0] er overflødig i denne:
intakes[intakes['boreholeno']== i].intakeno.unique()[0]!=None
Er fejlen der endnu? Kan jeg genskabe den?

**Comment by mapcentia** [comment]
@olemunch Nej, det kan jeg ikke. Lukker
