### ISSUE TITLE
Afspilning af projekter

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#161]
Anni har lavet en række projekter under dette brugernavn og PW
ANNN@skivekommune.dk
Kodeord:       SkiveGrundvand1
Ved afspilning kommer graferne 2 gange - sikker fordi de både er på tidsserielisten for egne tidsserier og på projekttidsserierlisten.

**Comment by mapcentia** [comment]
@JacobBirk Jeg går ud fra at det er dette du henviser til. At her er Grønning - VØ vist tre gange i listen:
![image](https://user-images.githubusercontent.com/3850918/94917950-e0130f00-04b1-11eb-956c-3fc06479963a.png)

**Comment by mapcentia** [comment]
Note: Dette sker når man opdaterer projektet. Så gemmes profilen endnu en gang i projektet

**Comment by mapcentia** [comment]
@JacobBirk Jeg har set en funktion ind, som fjerner dupletter. Hvis man gen-gemmer et projekt, så skulle dupletter blive fjernet.
