### ISSUE TITLE
Sync with database will fail because of #125

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#170]
We've a function called "Sync med database" ("Sync with database"):

![image](https://user-images.githubusercontent.com/3850918/97854146-585f3100-1cf9-11eb-9a88-ee3cf49ac792.png)

It should fetch fresh data from the database and update the plots on the dashboard. It does work, but will probably fail during time because of #125 

It uses s SQL like this `SELECT * FROM sensor.sensordata_with_correction WHERE gid=1301` where `gid` is the surrogate key.

This concerns queries to both `sensor.sensordata_with_correction` and `chemicals.boreholes_time_series_with_chemicals`

So after implementing #125 this function should be updated.

**Comment by mapcentia** [comment]
@aswinm It seems to work with implementing #125, so closing
