### ISSUE TITLE
Fejl ved load af online stationer (produktion)

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#183]
CALYPSO fejler når jeg vælger online stationer i opstart
![image](https://user-images.githubusercontent.com/50234893/101598447-760a6f00-39f8-11eb-9e18-78b490a131c9.png)
Stationer fremkommer ikke før der trykkes "anvend" i datamenuen igen
![image](https://user-images.githubusercontent.com/50234893/101598480-8589b800-39f8-11eb-892f-d948c4533604.png)

**Comment by mapcentia** [comment]
@JacobBirk Jeg kan ikke umiddelbart genskabe denne situation:
![Peek 2020-12-09 10-13](https://user-images.githubusercontent.com/3850918/101609516-562e7780-3a07-11eb-813f-de96ceb7615b.gif)

**Comment by JacobBirk** [comment]
Det kan jeg heller ikke. Underlidt -  det var også et problem i går



Med venlig hilsen

Jacob Birk Jensen

Partner

M: +45 28 43 07 10 (direkte)

T: +45 28 43 51 00

E: jbj@watsonc.dk


[cid:e0f3a432-458c-490f-9f29-4e623eb976eb]

Alfred Nobels Vej 21A

9220 Aalborg Ø


www.watsonc.dk<http://www.watsonc.dk/>


[cid:f884b0fd-9f37-4642-8433-41e3732820ea]<https://www.facebook.com/videnomvand/> [cid:a0a0659d-1af1-497b-a662-b1b6005023a1] <https://www.linkedin.com/company/18273976/>

________________________________
Fra: MapCentia <notifications@github.com>
Sendt: 9. december 2020 10:15
Til: mapcentia/watsonc <watsonc@noreply.github.com>
Cc: Jacob Birk Jensen <jbj@watsonc.dk>; Mention <mention@noreply.github.com>
Emne: Re: [mapcentia/watsonc] Fejl ved load af online stationer (produktion) (#183)


@JacobBirk<https://github.com/JacobBirk> Jeg kan ikke umiddelbart genskabe denne situation:
[Peek 2020-12-09 10-13]<https://user-images.githubusercontent.com/3850918/101609516-562e7780-3a07-11eb-813f-de96ceb7615b.gif>
