### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by mapcentia** [mapcentia/watsonc#186]

**Comment by olemunch** [comment]
Ved opstart af calypso - før valg i opstartsmenu - siger heap memory 142 mb på min profil
Jeg har ofte et problem når jeg søger på en boring:
- vælger jupiter, nitrat
- søger på 42.161 - boringen kommer fint frem
- prøver at zoome ud igen. Her bliver browseren helt nedlagt. Crome bruger ALT hukommelse og CPU og falder ikke ned igen
![image](https://user-images.githubusercontent.com/51031638/104289983-0b969400-54ba-11eb-9881-ef942c56d2ed.png)

**Comment by mapcentia** [comment]
@olemunch @JacobBirk Denne tog lidt tid at finde ud af. Det sker kun under bestemte forhold:
- Søgningen skal ske som det første, dvs. at kortets tilstand ikke må ændres inden søgningen.
- Søgningen skal ligge indenfor start extent.
- Efter søgning skal der som det første zoom ud. Der må ikke panes inden.
- Skal bruge en Chromebaseret browser.

Det skyldes en Leaflet bug, som har eksisteret nærmest altid: https://github.com/Leaflet/Leaflet/issues/3249

Et fix er at slå en animations-effekt fra ved zoom, som giver en smooth overgang mellem zoom-levels.

**Comment by olemunch** [comment]
Fedt at du har fundet frem til fejlen og en mulig løsning.

Kan en alternativ løsning være, at der slet ikke zoomes ind til den boring der søges på men bare panorerer og markerer boringen?



Med venlig hilsen
Ole Munch Johansen
M: +45 28 43 92 95 (direkte)
T:  +45 28 43 51 00
E: omu@WatsonC.dk<mailto:omu@WatsonC.dk>
[cid:b8d926bf-4d32-4eb2-8fb7-e3d5ee52e470]
Alfred Nobelsvej 21A
9220 Aalborg Ø
www.WatsonC.dk<http://www.watsonc.dk/>

[cid:08309a9c-9bdf-421f-9912-83325b9e9b72]<https://www.facebook.com/videnomvand/>[cid:c2333ebd-3bc0-445f-9829-57ff12761307]<https://www.linkedin.com/company/watsonc/>

________________________________
Fra: MapCentia <notifications@github.com>
Sendt: 18. januar 2021 09:33
Til: mapcentia/watsonc <watsonc@noreply.github.com>
Cc: Ole Munch Johansen <omu@watsonc.dk>; Mention <mention@noreply.github.com>
Emne: Re: [mapcentia/watsonc] Hukommelsesoptimering (#186)


@olemunch<https://github.com/olemunch> @JacobBirk<https://github.com/JacobBirk> Denne tog lidt tid at finde ud af. Det sker kun under bestemte forhold:

  *   Søgningen skal ske som det første, dvs. at kortets tilstand ikke må ændres inden søgningen.
  *   Søgningen skal ligge indenfor start extent.
  *   Efter søgning skal der som det første zoom ud. Der må ikke panes inden.
  *   Skal bruge en Chromebaseret browser.

Det skyldes en Leaflet bug, som har eksisteret nærmest altid: Leaflet/Leaflet#3249<https://github.com/Leaflet/Leaflet/issues/3249>

Et fix er at slå en animations-effekt fra ved zoom, som giver en smooth overgang mellem zoom-levels.

**Comment by mapcentia** [comment]
Man kan godt lave en "pan to" i stedet for "zoom to"

**Comment by olemunch** [comment]
@Jacob Birk Jensen<mailto:jbj@watsonc.dk>

Nogle gange synes jeg, at calypso zoomer for langt ind når man søger på en boring. Ville det være en løsning, at man bare panorerer til boringen når man søger en boring frem og fastholder aktuelt zoomniveau. Det vil samtidig løse martins udfordring med at der skiftes zoomniveau uden at det registreres.


Med venlig hilsen
Ole Munch Johansen
M: +45 28 43 92 95 (direkte)
T:  +45 28 43 51 00
E: omu@WatsonC.dk<mailto:omu@WatsonC.dk>
[cid:b5463092-2796-421c-b660-02b7263a35f9]
Alfred Nobelsvej 21A
9220 Aalborg Ø
www.WatsonC.dk<http://www.watsonc.dk/>

[cid:483c89d6-2037-4b7e-b2d5-1ed5ecbd5654]<https://www.facebook.com/videnomvand/>[cid:cec1c0c9-0760-4a82-a62b-569839c5ef10]<https://www.linkedin.com/company/watsonc/>

________________________________
Fra: MapCentia <notifications@github.com>
Sendt: 18. januar 2021 10:01
Til: mapcentia/watsonc <watsonc@noreply.github.com>
Cc: Ole Munch Johansen <omu@watsonc.dk>; Mention <mention@noreply.github.com>
Emne: Re: [mapcentia/watsonc] Hukommelsesoptimering (#186)


Man kan godt lave en "pan to" i stedet for "zoom to"
