### ISSUE TITLE
Layer & data: Ny gruppering af data i datamenu

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#191]
Vi skal have lavet en underinddeling af lag i vores datavælger.
![image](https://user-images.githubusercontent.com/50234893/106350803-10d84900-62d8-11eb-8651-2007cc54f339.png)

1. @olemunch skal have lavet en et "type kolonne" som kan laves som en for-filtrering af "overfladevand"
2. Vandløb, hav og bassiner skal kunne vælges enkeltvis (der er jo bare en filter på type kolonnen, men vi vil gerne skjult filteret, så det fremstår som et selvstændig lag.
3.  Vandløb, hav og bassiner skal have samme symbol men forskellige farver

**Comment by olemunch** [comment]
Der er oprettet et nyt skema i watsonc-databasen som hedder calypso_stationer
med følgende underinddelinger af sensordata_with_correction

Lagene er ikke stylet (kun midlertidigt) og der er ikke oprette noget i jupiterdatabasen

@mapcentia: Vil du hjælpe med styling og oprette fremmetabeller i jupiter. Skal de ind i samme skema som jupiterlagene og grupperes sammen med dem?


![image](https://user-images.githubusercontent.com/51031638/114355817-34d5c780-9b70-11eb-83c3-97b19a0cb975.png)
