### ISSUE TITLE
Layer & data: Filter by period and number of measurements

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#194]
Vi skal have lavet et globalt filter der går på tværs af alle valg og som kun giver os punkter inden for en given periode og som indeholder flere datapunkter end et kriterie. Vælges fx jupiter boringer med nitrat og online grundvandsstationer skal der kun vises de jupiterboringer og online stationer der har hhv nitratmålinger og onlinemålinger inden for perioden og som har flere målinger end det angivne kriterie
![image](https://user-images.githubusercontent.com/50234893/106351575-7e3aa880-62dd-11eb-9756-4db8252032d4.png)

Filter placeres nederst til venstre i datamenuen

1. @olemunch Skal vi vedligeholde en "Antal data punkter, datastart og dataslut" kolonne i databasen?

**Comment by olemunch** [comment]
@mapcentia 
For alle jupiterlag (kemi + vandstand) og sensordata_with_correction er der nu for vektorlag og rasterlag beregnet
 count (globalt filter)
startdate (globalt filter)
enddate (globalt filter)
derudover er der for alle jupiterlag beregnet
drilldepth (boringsdybde bruges som filter på jupiterlag og pesticidoverblik)
use (filter på jupiterlag og pesticidoverblik samt bruges til et nyt selvstændigt lag hvor vi inddeler boringer i kategorier på baggrund af anvendelse (use))

Der mangler at blive beregnet værdier for globalt filter for pesticidoverblikket men kolonnerne er oprettet

Jeg har ikke tilføjet de nye kolonner "startdate" og "enddate" i fremmedtabellerne i jupiter - det har du vist et script til Martin?

Så det betyder altså at du gerne må færdiggøre det globale filter for jupiterlag og sensordata og pesticidoverblik
