### ISSUE TITLE
Valg af jupiter - uden stof giver problemer

### ISSUE THREAD

**Issue by olemunch** [mapcentia/watsonc#198]
Når man vælger jupiter laget uden stof prøver applikationen at hente et lag i et loop... MH du ved hvad det sker :-)

Fejlen betyder fx at datamenuer ikke kan åbnes og applikationen kommer til at sidde fast i fejlen

**Comment by mapcentia** [comment]
@olemunch Er fixed. Vandstand er nu valgt fra starten således det ikke er muligt at starte uden stof. Endvidere ses Vandstands-muligheden ikke, hvis ikke Jupiter Boringer er valgt.

Er rullet ud på prod
