### ISSUE TITLE
Pesticidoverblik skal ind i jupiter oversigten

### ISSUE THREAD

**Issue by mapcentia** [mapcentia/watsonc#209]
Skal styres fra GC2 Meta

**Comment by olemunch** [comment]
Hej @mapcentia 
T.O.: @JacobBirk 

Jeg har lagt pesticidoverblik ind i jupiter.calypso_stationer
 som et view. Det er muligvis ikke den rigtige måde da det jo overskrives hvis jeg henter hele skemaet over igen fra watsonc.
Jeg har skrevet rb_grp1 i kommentarfeltet for at fortælle, at pesticidoverblik skal indgå sammen med jupiter-laget i en radiobutton.

Vi skal have Kommunikeret med Aswin omkring denne opstartsmenu og forklaret det nødvendige. 
Hvordan fungerer metadata api'et. Vil du vise hvordan han kan trække nedenstående info (screendump)

![image](https://user-images.githubusercontent.com/51031638/116003985-fd9bf780-a600-11eb-88dc-bb020ed3255d.png)

**Comment by olemunch** [comment]
Er udført
