### ISSUE TITLE
symbolstørrelse efter zoomniveau

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#22]

**Comment by mapcentia** [comment]
@JacobBirk Denne er lavet. GC2 havde ikke mulighed for at sætte en minimum størrelse på ikoner, så det blev jeg nødt til at lave. Der var kun mulighed for at sætte maksimum størrelse. Disse er nu sat til hhv. 7px og 20px. Ved 1:500.000 har de fuld størrelse.

**Comment by JacobBirk** [comment]
Ser godt ud.
Kan du lave det på sensordata også ?

**Comment by mapcentia** [comment]
@JacobBirk Det er lidt mere tricky, da det er vektor-symboler, så det er selve Calypso applikationen dette skal ske i og ikke i GC2. Det kan godt lade sig gøre tænker jeg. Jeg lukker denne her og så kan I åbne en ny med skalering af vektor-symboler.
