### ISSUE TITLE
implementer gruppering i parameterliste i dashboard

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#236]
Brug Jupiter kategori for jupiter boringer
Brug "vandstand", "vandføring", "temperatur", "ilt", mm for IOT stationer (har vi den kategorisering ?)
![image](https://user-images.githubusercontent.com/50234893/164178366-3d222c36-7295-4311-81c5-9c823aef2e58.png)

**Comment by MathiasBuus** [comment]
Har lavet alternativ løsning - den kan vi vende en dag Jacob
