### ISSUE TITLE
Opdatering af data i tidsserier i dashboard

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#24]
Opdatering af data i tidsserier i dashboard hvert minut og ved opstart

**Comment by mapcentia** [comment]
@JacobBirk Alexander var ikke kommet så langt med denne her som jeg troede. Han havde blot gjort klar til implementeringen.
Men der var en funktion til retablering af dashboardet, som jeg har anvendt. Dog bevirker det, at grafernes tilstand bliver nulstillet, da grafer bliver gendannet. Fx hvis man har zoomet ind, vil grafen bliver zoomet ud igen. Derfor er det ikke hensigtsmæsigt at opdatere automatisk fx hver 10 minut. Jeg har derfor lavet en knap, som opdaterer alle grafer - også dem, som ikke er på dashboardet.

**Comment by JacobBirk** [comment]
Lyder som en god løsning👍

Jacob
________________________________
Fra: MapCentia <notifications@github.com>
Sendt: Wednesday, November 20, 2019 3:09:16 PM
Til: mapcentia/watsonc <watsonc@noreply.github.com>
Cc: Jacob Birk Jensen <jbj@watsonc.dk>; Mention <mention@noreply.github.com>
Emne: Re: [mapcentia/watsonc] Opdatering af data i tidsserier i dashboard (#24)


Closed #24<https://github.com/mapcentia/watsonc/issues/24>.
