### ISSUE TITLE
Bug ved visning af nedbør

### ISSUE THREAD

**Issue by ksnwatsonc** [mapcentia/watsonc#26]
Når man opretter en tidsserie og tilføjer en nedbørsmåling, så "låser" Calypso sig fast på denne målestation. Hvis man f.eks. tilføjer en nedbørsmåling fra St. Restrup, er det også datavinduet for denne der dukker op hvis man efterfølgende klikker på en anden målestation.

**Comment by mapcentia** [comment]
@JacobBirk Det er fixed. Det er egentlig en "gammel" fejl, men som i lazy load udgaven, fik indlæsningen af data til at stoppe, når man havde plottet nedbørsdata.
