### ISSUE TITLE
Lav Mine stationer som Quick Access

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#260]
Visning af et lag med organisationens egne IOT stationer via Quick Access
![image](https://user-images.githubusercontent.com/50234893/172198482-cc2ac376-4c09-42c1-afb0-2563fc8466a4.png)
@olemunch @MathiasBuus Kan vi danne et som Ole har lavet et til Aarhus uden en opsætning pr. kunde? Vi gør det jo i sensor appen.

Det vil give en enorm værdi for vores IOT kunder og måske det der skal lokke dem i CALYPSO

**Comment by olemunch** [comment]
Jeg tænker vi kan lave et stort samlet IOT lag som filtreres på baggrund af de lokalitetsrettigheder som bruges i sensorappen. Jeg er enig i at det vil være elegant
Ole
________________________________
Fra: JacobBirk ***@***.***>
Sendt: Monday, June 6, 2022 6:02:50 PM
Til: mapcentia/watsonc ***@***.***>
Cc: Ole Munch Johansen ***@***.***>; Assign ***@***.***>
Emne: [mapcentia/watsonc] Lav Mine stationer som Quick Access (Issue #260)


Visning af et lag med organisationens egne IOT stationer via Quick Access
[image]<https://user-images.githubusercontent.com/50234893/172198482-cc2ac376-4c09-42c1-afb0-2563fc8466a4.png>
@olemunch<https://github.com/olemunch> @MathiasBuus<https://github.com/MathiasBuus> Kan vi danne et som Ole har lavet et til Aarhus uden en opsætning pr. kunde? Vi gør det jo i sensor appen.

Det vil give en enorm værdi for vores IOT kunder og måske det der skal lokke dem i CALYPSO
