### ISSUE TITLE
Kun én y-akse ved sammenligning af vandføring og vandstand

### ISSUE THREAD

**Issue by ksnwatsonc** [mapcentia/watsonc#27]
Vandføring måles i liter/sekund mens vandstand måles i m. Det gør det svært at samstille de to på en graf, da der opereres med helt forskellige tal og intervaller. Kan vi få implementeret en ekstra y-akse, som der også er ved visning af nedbør sammen med vandstand?

<img width="750" alt="vandføriong bug" src="https://user-images.githubusercontent.com/50231643/68864525-9b438580-06f1-11ea-84f5-74d448937d78.PNG">

**Comment by olemunch** [comment]
Jeg har nogle ønsker til dette og det er ikke noget Martin skal gøre før vi har aftalt hvordan det løses
/Ole
