### ISSUE TITLE
Farvesætning i kort og datamenu

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#28]
Grøn/grøn ved alle målinger under detektionsgrænsen
Kun vestre side hvid hvis der er en måling

![image](https://user-images.githubusercontent.com/50234893/69058228-91809180-0a13-11ea-8ec9-05d78633963c.png)

**Comment by mapcentia** [comment]
@JacobBirk Er det ikke kortet, som viser det rigtige symbol her for "Atrazin, desethyl-" ?
![image](https://user-images.githubusercontent.com/3850918/69541285-0fe7b100-0f89-11ea-9dcc-fd69fb4c40a6.png)

**Comment by JacobBirk** [comment]
@mapcentia Jo, i dette tilfælde.
Hvad med hvis alle målinger under detektionsgrænsen? Så har vi oplevet at symbolet slet ikke kommer frem

**Comment by mapcentia** [comment]
@JacobBirk Det skulle gerne virke nu med alle under attention nu . Jeg er lige ved at genregne alle værdier efter noget test, så der er pt. ingen data i test
