### ISSUE TITLE
Profilværktøj fejler

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#29]
Efter valg af model fås
![image](https://user-images.githubusercontent.com/50234893/69130825-7ebc9a00-0ab1-11ea-95f6-126fc040ac04.png)

**Comment by mapcentia** [comment]
![image](https://user-images.githubusercontent.com/3850918/69325956-481a8700-0c4b-11ea-9f31-3b2b01ba1369.png)

![image](https://user-images.githubusercontent.com/3850918/69339050-d0595600-0c64-11ea-8bb8-973bdc523e22.png)

**Comment by olemunch** [comment]
Jeg har testet følgende:

Dette profil melder fejl: JSONDecodeError: Extra data
{"status":"error","message":"Killed\n","process":["/bin/sh","-c","python3 /root/vidi/extensions/watsonc/scripts/profil/profiletool_kemi_v5.py \"{'coordinates':[[547638.8973195015,6316575.48458374],[552035.2389883252,6320374.66985411]],'DGU_nr':[' 34.  114',' 34. 1629',' 34. 1868',' 34. 2234',' 34. 2322',' 34. 2323',' 34. 2338',' 34. 2344',' 34. 2347',' 34. 2348',' 34. 2349',' 34. 2350',' 34. 2351',' 34. 2352',' 34. 2353',' 34. 2354',' 34. 2355',' 34. 2413',' 34. 2414',' 34. 2415',' 34. 2416',' 34. 2417',' 34. 2418',' 34. 2419',' 34. 2420',' 34. 2775',' 34. 2813',' 34. 3087',' 34. 3088',' 34. 3660',' 34.  392',' 34.  491'],'Profile_depth':-100,'layers':['/root/vidi/extensions/watsonc/scripts/intersection/../profil/FOHMJ_config.txt','/root/vidi/extensions/watsonc/scripts/intersection/../profil/Potentialekort_Aalborg_config.txt'],'overlap':[[[-5810,5810]],[[-5810,5810]]]}\""]}

Men hvis jeg sender denne json uden det afsluttende \""] til pythonscriptet får jeg ingen fejl:
{"coordinates":[[547638.8973195015,6316575.48458374],[552035.2389883252,6320374.66985411]],"DGU_nr":[" 34.  114"," 34. 1629"," 34. 1868"," 34. 2234"," 34. 2322"," 34. 2323"," 34. 2338"," 34. 2344"," 34. 2347"," 34. 2348"," 34. 2349"," 34. 2350"," 34. 2351"," 34. 2352"," 34. 2353"," 34. 2354"," 34. 2355"," 34. 2413"," 34. 2414"," 34. 2415"," 34. 2416"," 34. 2417"," 34. 2418"," 34. 2419"," 34. 2420"," 34. 2775"," 34. 2813"," 34. 3087"," 34. 3088"," 34. 3660"," 34.  392"," 34.  491"],"Profile_depth":-100,"layers":["FOHMJ_config.txt","Potentialekort_Aalborg_config.txt"],"overlap":[[[-5810,5810]],[[-5810,5810]]]}

**Comment by mapcentia** [comment]
Umiddelbart får jeg ikke fejl. Her har jeg tegnet et ret langt profil. Kan du ikke sende et billede af dit profil og indstillingerne, så jeg kan prøve at genskabe fejlen?
![image](https://user-images.githubusercontent.com/3850918/69340211-3810a080-0c67-11ea-92f5-2bc39354a676.png)

**Comment by olemunch** [comment]
Jeg har ikke et billede da der kommer en fejl og profilet ikke bliver gemt - jeg kan prøve igen forfra og lave et screendump før jeg kører profilet.
Kan du ikke afvikle det med dette?
{"status":"error","message":"Killed\n","process":["/bin/sh","-c","python3 /root/vidi/extensions/watsonc/scripts/profil/profiletool_kemi_v5.py "{'coordinates':[[547638.8973195015,6316575.48458374],[552035.2389883252,6320374.66985411]],'DGU_nr':[' 34. 114',' 34. 1629',' 34. 1868',' 34. 2234',' 34. 2322',' 34. 2323',' 34. 2338',' 34. 2344',' 34. 2347',' 34. 2348',' 34. 2349',' 34. 2350',' 34. 2351',' 34. 2352',' 34. 2353',' 34. 2354',' 34. 2355',' 34. 2413',' 34. 2414',' 34. 2415',' 34. 2416',' 34. 2417',' 34. 2418',' 34. 2419',' 34. 2420',' 34. 2775',' 34. 2813',' 34. 3087',' 34. 3088',' 34. 3660',' 34. 392',' 34. 491'],'Profile_depth':-100,'layers':['/root/vidi/extensions/watsonc/scripts/intersection/../profil/FOHMJ_config.txt','/root/vidi/extensions/watsonc/scripts/intersection/../profil/Potentialekort_Aalborg_config.txt'],'overlap':[[[-5810,5810]],[[-5810,5810]]]}""]}

**Comment by olemunch** [comment]
Jacob fik lige en fejl 400, hvor der inde under profile response (i udviklerværktøjet) stod unauterized
Når jeg prøver at tegne Jacobs profil får jeg ikke samme fejl

![image](https://user-images.githubusercontent.com/51031638/69341903-b884d080-0c6a-11ea-84c3-4c5d2706e7ca.png)

**Comment by olemunch** [comment]
Profilet som fejlede med Error:Unauthorized hos Jacob så sådan ud:
![image](https://user-images.githubusercontent.com/51031638/69342174-419c0780-0c6b-11ea-982c-b13735830117.png)

**Comment by mapcentia** [comment]
Har @JacobBirk en aktiv session i Vidi? Hvis han "Clear site data", så bliver cookies også slettet (hvis fluebenet er sat)
