### ISSUE TITLE
Vandstand mangler i datamenu

### ISSUE THREAD

**Issue by olemunch** [mapcentia/watsonc#33]
@mapcentia 
Man kan ikke vælge vandstand i datamenuen når man er kommet ind i CALYPSO. Den kan godt vælges i opstartsmenu, men data vises pt ikke (27/11 2019)

Man må ikke kunne komme til at vælge vandstand i profilværktøjet så i den menu skal vandstand ikke blive tilgængelig

**Comment by mapcentia** [comment]
@olemunch Alexander havde slået vandstand fra i profilværktøjet, men det er samme komponent, der bruges i datamenuen. Nu tjekkes context.
