### ISSUE TITLE
Uforståelige titler på DGU-boringer

### ISSUE THREAD

**Issue by ksnwatsonc** [mapcentia/watsonc#34]
Navnene på de stoffer, der er placeret i tidsserier i datamenuen skifter navn. Fejlen opstår, når man klikker på en ny boring, efter at have tilføjet et stof til tidsserien.

<img width="237" alt="Bug - navne på boringer" src="https://user-images.githubusercontent.com/50231643/69791911-c6d07080-11c5-11ea-88ae-721548968c9b.PNG">

**Comment by JacobBirk** [comment]
samme som andet issue
