### ISSUE TITLE
DGU-søgning finder den forkerte boring

### ISSUE THREAD

**Issue by olemunch** [mapcentia/watsonc#35]
@mapcentia 
DGU-søgningen er pludselig begyndt at finde de forkerte boringer - hvad er ændret 27/11-2019?

**Comment by mapcentia** [comment]
@JacobBirk Når der bliver hentet en ny Jupiter database skal Elasticsearch indekset også opdateres. Det er gjort nu.

**Comment by JacobBirk** [comment]
Perfekt 👍

Jacob
________________________________
Fra: MapCentia <notifications@github.com>
Sendt: Thursday, November 28, 2019 5:33:36 PM
Til: mapcentia/watsonc <watsonc@noreply.github.com>
Cc: Jacob Birk Jensen <jbj@watsonc.dk>; Mention <mention@noreply.github.com>
Emne: Re: [mapcentia/watsonc] DGU-søgning finder den forkerte boring (#35)


@JacobBirk<https://github.com/JacobBirk> Når der bliver hentet en ny Jupiter database skal Elasticsearch indekset også opdateres. Det er gjort nu.
