### ISSUE TITLE
Projekter

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#39]
Et projekt skal være 
- kort med symboler
- Baggrundskort
- Alt der vises i dashboard (valgte tidsserier og profiler)

Tidsserier og profiler der ikke vises i dashboard skal ikke gemmes med i projektet

Ved load
- tidsserier og profiler på lister i højre menu og aktiveres på dashboard

**Comment by olemunch** [comment]
Når man åbner et projektlink så kan man ikke vælge nye stoffer i datamenuen og det stof, som var valgt da projektet blev gemt er ikke valgt (men vises).
Man kan ikke zoome ind og få mouseover på laget

**Comment by mapcentia** [comment]
@olemunch @JacobBirk Dette er lavet for tidsserier, men ikke profiler. Jeg lukker denne og har oprettet nyt issue ang. profiler #53 

Ole's bug i kommentar-feltet er lagt i #52
