### ISSUE TITLE
Nye stoffer vises ikke

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#41]
stoffet dimethylsulfamid er nyt på listen, men det virker ikke at der er genereret kort

**Comment by olemunch** [comment]
@mapcentia 
Følgende compundno er tilføjet listen i codes,compund , men vises ikke i kortet

3532
4945
6117

**Comment by JacobBirk** [comment]
@mapcentia fikser de tre stoffer snarest

**Comment by mapcentia** [comment]
@olemunch 3532 og 4945 har jeg fået beregnet. Men 6117 ser ud til ikke at findes i Jupiter database.
`select compoundno from pcjupiterxlplusviews.grwchemanalysis where compoundno = 6117 limit 1;` giver nul rækker.

Jeg har ikke skiftet over til den nyeste database endnu - det gør jeg senere.

**Comment by olemunch** [comment]
@mapcentia 

Hej Martin
Du har helt ret. Det viser sig, at det skulle have været 
N,N Dimehtylsulfamid 
Compoundno **4743**
Vil du lave den i stedet?

**Comment by mapcentia** [comment]
@olemunch Kan det passe, at du har taget 6117 ud?

**Comment by olemunch** [comment]
Ja det er rigtigt, det var den der blev erstattet af N,N Dimethyl... som jeg ikke lige husker nummeret på. 6117 skal ikke være med

Den 19. jan. 2020 kl. 16.19 skrev MapCentia <notifications@github.com<mailto:notifications@github.com>>:


@olemunch<https://github.com/olemunch> Kan det passe, at du har taget 6117 ud?
