### ISSUE TITLE
Nedbør kan ikke vises

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#44]
Der kommer ikke data i datamenuen

**Comment by olemunch** [comment]
@mapcentia 
Jeg har lige testet nedbør og finder ingen fejl 10/12 - 2019
Har du gjort noget med denne Martin?

**Comment by mapcentia** [comment]
@olemunch Jeg er faktisk ikke helt klar over hvad dette issue dækker over. Men hvis det ikke længere er relavant kan det vel lukkes?

**Comment by olemunch** [comment]
Vi opretter det igen og uddyber såfremt problemer "genopstår"
