### ISSUE TITLE
Mouseover på CALYPSO stationer

### ISSUE THREAD

**Issue by olemunch** [mapcentia/watsonc#46]
Har vi mulighed for at oprette en mouseover til CALYPSO-stationer som en ekstra JSON-kollonne i sensor.sensordata_with_correction

Der skal kunne stå diverse meta-data såsom:
Hvem ejer data, hvad er det for en location, hvad måles m.m.
Kan vi lave en struktur, som vi selv kan udfylde med relevante oplysninger?

**Comment by olemunch** [comment]
@mapcentia 
Der er tilføjet en kolonne til sensor.sensordata_with_correction
som hedder "mouseover"
Den er defineret som character varying og har en længde på 500 tegn.
Der er en defaultværdi på 'no available text'
Du må gerne løfte den over i sensordata_with_correction og sætte mouseover text på i testversion af calypso.

**Comment by mapcentia** [comment]
![image](https://user-images.githubusercontent.com/3850918/74316610-24fb0180-4d7a-11ea-8d20-d3e9c6dfb56d.png)
