### ISSUE TITLE
Browser compatibilitet

### ISSUE THREAD

**Issue by olemunch** [mapcentia/watsonc#50]
Calypso fungerer slet ikke i Edge

Nogle offentlige institutioner kan ikke få lov at installere crome. 

Vi bør vel understøtte:
Crome
Safari
Edge

som minium?

**Comment by mapcentia** [comment]
Edge 79 :heavy_check_mark: (Chrome based)
Edge 18 :heavy_check_mark:
Edge 17 :heavy_check_mark:
Edge 16 :x:
Edge 15 :x:
Firefox :heavy_check_mark:
Safari :heavy_check_mark:
