### ISSUE TITLE
Mouseover på grafer ved CALYPSO-stationer virker ikke

### ISSUE THREAD

**Issue by olemunch** [mapcentia/watsonc#51]
Mouseover på værdier på graferne er blevet disablet på et tidspunkt. Det skal de ikke være
Hvis kan kan se den del af koden hvor graferne bliver dannet så kan jeg sikker foreslå en ændring

**Comment by olemunch** [comment]
@mapcentia 
Søg på hoverinfo='none' i koden

**Comment by mapcentia** [comment]
fixed https://github.com/mapcentia/watsonc/commit/7fa06f71ee68b535bc15f50f9bcc943d1dd210a5
