### ISSUE TITLE
Åbner ikke data menu korrekt

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#62]
@mapcentia Nu kan datamenuen åbnes for grå punkter, men hvis punktet samtidig er en calypso station åbnes stationen ikke korrekt. Datamenuen for det sidste grå punkt der har været klikket på åbner i stedet
![image](https://user-images.githubusercontent.com/50234893/72684255-43edd700-3adf-11ea-9f0b-72cbbb45139f.png)

**Comment by olemunch** [comment]
@mapcentia 
Opskrift på at fremkalde dette problem
- vælg jupiter + pH
-vælg calypso nedbør
- zoom til dgu 6.965
- zoom ud så nedbørsstationen og boringen ligger tæt på hinanden
- klik midt mellem dråben og boringen så begge fanges

Prøv evt dette projekt
https://map.calypso.watsonc.dk/app/jupiter/chemicals,sensor,system/?state=state_snapshot_9e8df700-3c22-11ea-9c0e-218a72d6b209

**Comment by mapcentia** [comment]
@JacobBirk @olemunch Jeg har genskabt fejlen. Der opstår en JavaScript fejl, efter man har klikket mellem de to punkter. Jeg har lavet et hurtigt fix ved at undertrykke fejlen. Jeg er i gang med at rulle ud

**Comment by olemunch** [comment]
Hej Martin

Er der nogen risiko for at det afføder andre fejl? Så vil vi nemlig ikke have det på produktion lige nu da vi skal lave demo over middag for Århus Kommune

Med venlig hilsen
Ole Munch Johansen
M: +45 28 43 92 95 (direkte)
T:  +45 28 43 51 00
E: omu@WatsonC.dk<mailto:omu@WatsonC.dk>
[cid:e8109a0e-d1a3-456b-84ce-7818663b9adb]
Alfred Nobelsvej 21A
9220 Aalborg Ø
www.WatsonC.dk<http://www.watsonc.dk/>

[cid:990e72e2-607c-4fbb-904d-8d7a4135ac87]<https://www.facebook.com/videnomvand/>[cid:6ea946fa-0ae0-4dbb-9a86-a2c0a6e4f259]<https://www.linkedin.com/company/watsonc/>

________________________________
Fra: MapCentia <notifications@github.com>
Sendt: 21. januar 2020 09:27
Til: mapcentia/watsonc <watsonc@noreply.github.com>
Cc: Ole Munch Johansen <omu@watsonc.dk>; Mention <mention@noreply.github.com>
Emne: Re: [mapcentia/watsonc] Åbner ikke data menu korrekt (#62)


@JacobBirk<https://github.com/JacobBirk> @olemunch<https://github.com/olemunch> Jeg har genskabt fejlen. Der opstår en JavaScript fejl, efter man har klikket mellem de to punkter. Jeg har lavet et hurtigt fix ved at undertrykke fejlen. Jeg er i gang med at rulle ud

**Comment by mapcentia** [comment]
@olemunch Nej, jeg har blot lavet en `try catch` om den kode, der stoppede scriptet: https://github.com/mapcentia/watsonc/commit/30eca2a5ce465d185913a0ff4516c4fdcabf0c2e

**Comment by mapcentia** [comment]
@JacobBirk @JacobBirk Rettelsen er rullet ud. Lav helllere en Clear Site Data.
Der er stadig problemet med, at man ikke kan fange en Station, hvis et borehul er tæt på, men fejlen gør nu ikke at problemet bliver hængende hvis man fx zoomer tættere på eller klikker på en helt anden station.

Note: Problemet består i at DGU nr. bliver sendt med, når der skal trækkes en station ud:
`https://map.calypso.watsonc.dk/api/sql/jupiter?srs=25832&q=SELECT * FROM sensor.sensordata_with_correction WHERE boreholeno in(' 34. 1408','312')`
Stations nr, er INT og Dgu nr. stregen giver så fejl i SQL SELECT'en

**Comment by mapcentia** [comment]
Fixed https://github.com/mapcentia/watsonc/commit/9aaac81ddbd24ac7ec680f3beb91725c8b258119
