### ISSUE TITLE
Profiltegning fejler

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#63]
@mapcentia Profilværktøjet fejler efter sidste opdatering

![image](https://user-images.githubusercontent.com/50234893/72708790-c1f3c180-3b63-11ea-9995-b7c66589e501.png)

**Comment by mapcentia** [comment]
@JacobBirk @olemunch Så virker det. Det var `FOHM_inventory.txt`, som fik jeres Python script til at crashe
