### ISSUE TITLE
Projekter åbner ikke korrekt i Edge

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#64]
@mapcentia 
Prøve flg. link
https://map.calypso.watsonc.dk/app/jupiter/chemicals,sensor,system/?state=state_snapshot_69e360b0-3b6b-11ea-b294-dd694928bf83 

NB. lavere prioritet end issue 62 og 63

**Comment by olemunch** [comment]
@olemunch 
Lav forklaring til dette
https://map.calypso.watsonc.dk/app/jupiter/chemicals,sensor,system/?state=state_snapshot_00688880-3dbf-11ea-bf9d-3306d6af0673
