### ISSUE TITLE
Map: Symboler og mouseover forkert for vandstand

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#66]
@mapcentia Når jupiter og vandstand vælges er symboler og mouseover forkert.
Symboler er altid fyldte uanset om der er 0, 1 eller flere målinger og mouse over er null

**Comment by mapcentia** [comment]
@JacobBirk Der er nu beregnet latest og max value på boreholes med waterlevel. Dem hvor latest og max er ens er hvid/blå og dem hvor de er forskellige er blå/blå. I første tilfælde antager vi, at der kun er én måling selv om, at der teoretisk set godt kan være flere målinger, som er ens. Men datamodellen giver ikke mulighed for at lagre antal målinger, da dette tal ikke anvendes til kemikalier.

**Comment by JacobBirk** [comment]
@mapcentia Det går galt med nogle boringer - se fx 87.558
Symbolet i datadialogen er ok, men ikke i kortet. Det går galt når maks er senest og det er vel også denne fejlmulighed du beskriver. Hvad kan vi gøre?
![image](https://user-images.githubusercontent.com/50234893/73361058-7bf5d680-42a4-11ea-94d2-6d97d15ae947.png)

**Comment by olemunch** [comment]
@mapcentia 
Vi ønsker at antallet af målinger med i datastrukturen så den bruges til at bestemme om der kommer en hvid halvdel med. Det gælder alle stoffer - ikke bare vandstand

**Comment by olemunch** [comment]
@mapcentia  Der er også fejl i symbolet i selve datamenuen - de vises altid som helt blå. JS kigges igennem...
