### ISSUE TITLE
Filterfarver på profiler

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#67]
@olemunch Jeg viser BAM på dette profil og alle filtre bliver gule, selvom kun enkelte filtre har detekteret værdier
![image](https://user-images.githubusercontent.com/50234893/73362458-2e2e9d80-42a7-11ea-8807-93b585ea5f7d.png)

**Comment by olemunch** [comment]
@jbj
Jeg har rettet fejlen, men kun testet på en enkelt boring. Jeg troede faktisk at farverne var korrekte for pesticider også. Nu overruler attributten "<" sådan at farven bliver grøn når der ikke er detekteret noget. 
![image](https://user-images.githubusercontent.com/51031638/73364350-b6627200-42aa-11ea-9062-5a5058553642.png)

**Comment by JacobBirk** [comment]
Fedt. Hvad skal der til for at rulle det ud?
________________________________
Fra: Ole Munch Johansen <notifications@github.com>
Sendt: 29. januar 2020 15:20
Til: mapcentia/watsonc <watsonc@noreply.github.com>
Cc: Jacob Birk Jensen <jbj@watsonc.dk>; Author <author@noreply.github.com>
Emne: Re: [mapcentia/watsonc] Filterfarver på profiler (#67)


@jbj<https://github.com/jbj>
Jeg har rettet fejlen, men kun testet på en enkelt boring. Jeg troede faktisk at farverne var korrekte for pesticider også. Nu overruler attributten "<" sådan at farven bliver grøn når der ikke er detekteret noget.
[image]<https://user-images.githubusercontent.com/51031638/73364350-b6627200-42aa-11ea-9062-5a5058553642.png>

**Comment by olemunch** [comment]
@mapcentia 
Martin ændringen er lagt på Github og kommer vel med automatisk når du ruller en ny version ud? Jacob vil gerne have den ud når det er muligt

**Comment by JacobBirk** [comment]
@olemunch 
Når jeg viser N,N-Dimethylsulfamid (DMS) på profil siger mouse over "ingen målinger" selv om der er målinger

**Comment by olemunch** [comment]
@JacobBirk 
Ja det er fordi det view profilværktøjet bruger ikke automatisk opdaterer listen af stoffer.
Det skal jeg have ændret
