### ISSUE TITLE
Profiles should be included in projects as time series does

### ISSUE THREAD

**Issue by mapcentia** [mapcentia/watsonc#81]
Create a profile and time series:
![image](https://user-images.githubusercontent.com/3850918/76745648-8a298480-6776-11ea-8b1a-327776992741.png)

The create a Project (need to be signed in):
![image](https://user-images.githubusercontent.com/3850918/76745897-e55b7700-6776-11ea-8cb1-5c959abef8d0.png)

Now copy project link:
![image](https://user-images.githubusercontent.com/3850918/76746156-5733c080-6777-11ea-9bae-1467b3606ba4.png)

Open the project link in a browser where you're not signed in. Then you see the project only includes the time serie. This is by design and not a bug. But we now need to include the Profile plot in projects.
![image](https://user-images.githubusercontent.com/3850918/76746411-c3aebf80-6777-11ea-85e2-12ebc894cc8d.png)

**Comment by mapcentia** [comment]
@aswinm 
When I create a Project like:
![image](https://user-images.githubusercontent.com/3850918/77998620-a3fbc780-7331-11ea-8307-ad0014340546.png)
I expect to get get both the Profile and Timeseries on the Dashboard, when opening the project (not logged in), but I get just the timeseries. The Profile is in the list, but it doesn't appear on the Dashboard when checked on:
![image](https://user-images.githubusercontent.com/3850918/77998842-01901400-7332-11ea-8027-85c41fada791.png)

**Comment by mapcentia** [comment]
@aswinm 
It seems that the Profiles are included in Projects as a whole and not by reference. Profiles should be includes as a reference just like Plots:
![image](https://user-images.githubusercontent.com/3850918/78000189-31401b80-7334-11ea-8c19-731b0ac617fa.png)

**Comment by mapcentia** [comment]
@aswinm 
Only Profiles and Timeseries on the Dashboard should be referenced in a Project.

Now, if I've some Profiles/Timeseries, which are not on the Dashboard:
![image](https://user-images.githubusercontent.com/3850918/79346091-37d4b280-7f32-11ea-8285-dc485d7bc45e.png)

And creating a Project and opens the project link I get the Profiles on the Dashboard:
![image](https://user-images.githubusercontent.com/3850918/79346322-7ff3d500-7f32-11ea-864c-ec4ac0682151.png)

So It seems, that projects now takes all Profiles/Timeseries regardless if they are on the Dashboard or not, and references them it the project.

**Comment by aswinm** [comment]
Do you mean existing Profiles or Time Series created previously by the user and not part of the project? 

Can you explain it a bit more?

**Comment by mapcentia** [comment]
@aswinm It seems to work now. But when activating a your own project, the Profile plot gets on the Dashboard twice. The checkbox is checked in both list, which are fine:

![image](https://user-images.githubusercontent.com/3850918/79564223-8444fd00-80ae-11ea-9b92-2928faf98d05.png)

For timeseries it works - only one plot is shown. But the checkboxes is not checked, which they should:

![image](https://user-images.githubusercontent.com/3850918/79564806-9ffcd300-80af-11ea-8cc8-420e89d72fc9.png)
