### ISSUE TITLE
Farvegivning af symboler forkert i datamenu

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#89]
@mapcentia 
Farvegivning i kort er korrekt, men ikke i data menu - se eksempel
fx
Noring: 59.288
Stof: Atrasin, Desisopropy
Korrekte farver: gul-grøn

![image](https://user-images.githubusercontent.com/50234893/78101622-60b06000-73e8-11ea-869b-6251e9ed4cba.png)

![image](https://user-images.githubusercontent.com/50234893/78101532-116a2f80-73e8-11ea-8552-68c837820c07.png)

**Comment by mapcentia** [comment]
@JacobBirk @olemunch Detektionsgrænsen er ikke pt. at finde i mouse-over data, men den er nu med i modal dialogen:

![image](https://user-images.githubusercontent.com/3850918/85411264-668d8b80-b568-11ea-8ea2-c9e7056b8250.png)
