### ISSUE TITLE
Map: Klik fanger ikke både DGU boringer og Calypso stationer

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#90]
@mapcentia Ved klik på en boringer med en Calypso station fanger vi ikke både DGU boringer og Calypso stationer
![image](https://user-images.githubusercontent.com/50234893/78339423-c2153200-7594-11ea-8512-226971eae47e.png)

**Comment by mapcentia** [comment]
Forsøg med en pop-up, der lister lag med hits. I pop-up vælges hvilke lag der skal anvendes i dialog.
