### ISSUE TITLE
Stationsnavne på faneblade

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#94]
Giv fanerne de rigtige navne og brug evt kun fanerne og ikke navnet øverst
![image](https://user-images.githubusercontent.com/50234893/79204413-d0890680-7e3c-11ea-91bb-818b47e9344a.png)

**Comment by mapcentia** [comment]
@JacobBirk @olemunch Fanerne har nu de rigtige navne, men det virker ikke på Nedbør. På de andre stationer og Jupiter kan navnet tages fra selve measurement objektet:

![image](https://user-images.githubusercontent.com/3850918/84743160-d53f7780-afb1-11ea-80ae-1e71b38670d1.png)

Men dette objekt er tomt på Nedbør stationerne:
![image](https://user-images.githubusercontent.com/3850918/84743269-fdc77180-afb1-11ea-9bfc-cbbaaaf4f02e.png)

**Comment by olemunch** [comment]
@mapcentia 
sensor.sensordata_with_correction.alias er opdateret med rigtige navne for alle lokaliteter

**Comment by mapcentia** [comment]
@olemunch Virker fint. Lukker
