### ISSUE TITLE
Profiler fejler

### ISSUE THREAD

**Issue by JacobBirk** [mapcentia/watsonc#97]
@mapcentia @olemunch profilværktøjet fejler. Er det stadig pejlinger uden datostempel?

![image](https://user-images.githubusercontent.com/50234893/79458517-336fce80-7ff2-11ea-9ccf-adbf5c793836.png)

**Comment by mapcentia** [comment]
@JacobBirk @olemunch Jeg kan godt lave et profil på Fyn. Vi skal have fisket fejlen fra Python scriptet ud.

**Comment by JacobBirk** [comment]
Fyn fejler også hos mig
________________________________
Fra: MapCentia <notifications@github.com>
Sendt: 16. april 2020 15:08
Til: mapcentia/watsonc <watsonc@noreply.github.com>
Cc: Jacob Birk Jensen <jbj@watsonc.dk>; Mention <mention@noreply.github.com>
Emne: Re: [mapcentia/watsonc] Profiler fejler (#97)


@JacobBirk<https://github.com/JacobBirk> @olemunch<https://github.com/olemunch> Jeg kan godt lave et profil på Fyn. Vi skal have fisket fejlen fra Python scriptet ud.

**Comment by olemunch** [comment]
Er jupiterdatabasen blevet opdateret?  Så er der et materialized view som skal opdateres. Det lyder ikke som samme fejl hvis den fejler så hyppigt.
Ole

Den 16. apr. 2020 kl. 14.55 skrev JacobBirk <notifications@github.com<mailto:notifications@github.com>>:


@mapcentia<https://github.com/mapcentia> @olemunch<https://github.com/olemunch> profilværktøjet fejler. Er det stadig pejlinger uden datostempel?

[image]<https://user-images.githubusercontent.com/50234893/79458517-336fce80-7ff2-11ea-9ccf-adbf5c793836.png>

**Comment by mapcentia** [comment]
Jupiter db er skiftet over til 140420, men jeg har lige gjort det

Martin Høgh

mapcentia.com
+45 26277810
Skype: mhoegh1
about.me/mhoegh

**Comment by JacobBirk** [comment]
@mapcentia 
Det er kun mig der oplever problemer og det skyldes åbenbart autorisation  
![image](https://user-images.githubusercontent.com/50234893/79555974-b3ed0880-80a0-11ea-8aa4-aa2fa8c08e19.png)
Kan det hjælpe ?
